### ISSUE TITLE
some data is missing

### ISSUE THREAD

**Issue by ForrestPi** [NikitaBogoslovskiy/AvatarAnimation#1]
Hi, could you provide release_data.pkl and IKModel.pt ?

**Comment by NikitaBogoslovskiy** [comment]
Hi! I've uploaded all necessary files (including release_data.pkl and IKModel.pt) on Google Drive and added link to files/files_link.txt. 
That link: https://drive.google.com/drive/folders/1QJj4WWapZh6IXSXznlW7LBotV1ttztBB?usp=share_link
You need to download these files and paste them in "files" folder. It's worth noting that I haven't uploaded dataset file which can be useful for training (dataset.pkl) because it's quite heavy (7.3 Gb). If you need it too, text me and I'll send you.
Also I did a small fix in this project so it`s better to pull new commits.
